exports.E_INTERNAL_ERROR													="E_INTERNAL_ERROR";
exports.E_EMAIL_ALREADY_USED												="E_EMAIL_ALREADY_USED";
exports.E_EMAIL_FORMAT_INVALID												="E_EMAIL_FORMAT_INVALID";
exports.E_PASSWORD_FORMAT_INVALID											="E_PASSWORD_FORMAT_INVALID";
exports.E_MISSING_PARAMETER													="E_MISSING_PARAMETER";
exports.E_UNDEFINED_USER													="E_UNDEFINED_USER";
exports.E_WRONG_PASSWORD													="E_WRONG_PASSWORD";
exports.E_PERMISSION_DOESNT_EXIST                                           ="E_PERMISSION_DOESNT_EXIST";